export default {
  ADD_NOTE: 'ADD_NOTE',
  GET_NOTE: 'GET_NOTE',
  SWITCH_NOTE: 'SWITCH_NOTE',
  SAVE_NOTE: 'SAVE_NOTE',
  UPDATE_NOTE: 'UPDATE_NOTE',
  SYNC_NOTE_REQUEST: 'SYNC_NOTE_REQUEST',
  SYNC_NOTE_SUCCESS: 'SYNC_NOTE_SUCCESS',
  SYNC_NOTE_FAILED: 'SYNC_NOTE_FAILED',
  // 以上为旧版的笔记管理系统 已弃置

  CREATE_NOTE: 'CREATE_NOTE',
  GET_USER_NOTES: 'GET_USER_NOTES',
  SYNC_NOTE: 'SYNC_NOTE',
  MARK_UNSYNC_NOTE: 'MARK_UNSYNC_NOTE',
};
