export default {
  SET_USER_SETTINGS: 'SET_USER_SETTINGS',
  SET_SYSTEM_SETTINGS: 'SET_SYSTEM_SETTINGS',
  UPDATE_NOTIFICATION_PERMISSION: 'UPDATE_NOTIFICATION_PERMISSION',
  UPDATE_CONFIG: 'UPDATE_CONFIG',
  ADD_FAVORITE_DICE: 'ADD_FAVORITE_DICE',
  REMOVE_FAVORITE_DICE: 'REMOVE_FAVORITE_DICE',
  UPDATE_FAVORITE_DICE: 'UPDATE_FAVORITE_DICE',
  FETCH_REMOTE_SETTINGS: 'FETCH_REMOTE_SETTINGS',
};
