// coc7职业信息
// http://static.moonrailgun.com/doc/%E5%85%8B%E8%8B%8F%E9%B2%81%E7%9A%84%E5%91%BC%E5%94%A4%E7%AC%AC%E4%B8%83%E7%89%88%E8%B0%83%E6%9F%A5%E5%91%98%E6%89%8B%E5%86%8C1.21.pdf

const job = [
  {
    name: '会计师',
    desc:
      '会计师可能在企业工作或作为自由会计师，为个体经营者和企业客户担任顾问。他们是优秀的研究者，既勤奋又关注细节，能够通过仔细分析个人和企业交易记录、财务报表和其他记录支援其他调查员。',
    credit: [30, 70],
    duty: ['会计', '法律', '图书馆', '聆听', '说服', '侦查'],
    dutySkill: '教育*4',
    dutySkillExt: '任意其他两项个人或时代特长',
  },
  {
    name: '杂技演员',
    desc:
      '杂技演员可能是参加各级比赛（甚至奥运会）的业余运动员，也可能是专业的演员，在马戏团、嘉年华、歌舞团之类的地方作为娱乐业从业者工作。',
    credit: [9, 20],
    duty: ['攀爬', '闪避', '跳跃', '投掷', '侦查', '游泳'],
    dutySkill: '教育*2+敏捷*2',
    dutySkillExt: '任意其他两项个人或时代特长',
  },
  {
    name: '演员-戏剧演员',
    desc:
      '一般指舞台剧演员和电影演员。许多演员有相当深厚的文化素养，认为自己才是“正统”的，倾向于轻视电影业的商业活动。直到 20 世纪后期电影业的地位提高，电影演员的薪酬增加，这种情况才发生改变。电影业和电影明星一直是世界人民关注的焦点。许多明星一夜成名，在媒体的聚光灯下过着光鲜亮丽的生活。在 1920 年代，虽然全国都有大型剧院，美国的戏剧中心仍然是纽约城。英国的情况与之相近，戏剧的中心在伦敦，其他的剧团则在各郡作巡回演出。巡回剧团乘火车旅行，演出内容既包括新编剧目，也包括莎士比亚和其他人的传统剧目。有些剧团也会花时间去国外采风，通常是去加拿大、夏威夷、澳大利亚和欧洲大陆。20 年代后期出现了有声电影，不少默片时代的明星难以适应有声电影的冲击，挥舞手臂的夸张扮演从此让位给了细致入微的角色特写。这段时间前期的明星包括约翰·加菲尔德和弗兰西斯·布什曼，后期则是贾莱·库珀和琼·克劳馥。',
    credit: [9, 40],
    duty: ['艺术（表演）', '乔装', '格斗', '历史'],
    dutySkill: '教育*2+外貌*2',
    dutySkillExt: '两项社交技能, 任意一项其他个人或时代特长',
    dutySkillOptions: ['魅惑', '话术', '恐吓', '说服'],
  },
  {
    name: '演员-电影演员',
    desc:
      '一般指舞台剧演员和电影演员。许多演员有相当深厚的文化素养，认为自己才是“正统”的，倾向于轻视电影业的商业活动。直到 20 世纪后期电影业的地位提高，电影演员的薪酬增加，这种情况才发生改变。电影业和电影明星一直是世界人民关注的焦点。许多明星一夜成名，在媒体的聚光灯下过着光鲜亮丽的生活。在 1920 年代，虽然全国都有大型剧院，美国的戏剧中心仍然是纽约城。英国的情况与之相近，戏剧的中心在伦敦，其他的剧团则在各郡作巡回演出。巡回剧团乘火车旅行，演出内容既包括新编剧目，也包括莎士比亚和其他人的传统剧目。有些剧团也会花时间去国外采风，通常是去加拿大、夏威夷、澳大利亚和欧洲大陆。20 年代后期出现了有声电影，不少默片时代的明星难以适应有声电影的冲击，挥舞手臂的夸张扮演从此让位给了细致入微的角色特写。这段时间前期的明星包括约翰·加菲尔德和弗兰西斯·布什曼，后期则是贾莱·库珀和琼·克劳馥。',
    credit: [20, 90],
    duty: ['艺术（表演）', '乔装', '汽车驾驶', '心理学'],
    dutySkill: '教育*2+外貌*2',
    dutySkillExt: '两项社交技能, 任意两项其他个人或时代特长',
    dutySkillOptions: ['魅惑', '话术', '恐吓', '说服'],
  },
  {
    name: '事务所侦探',
    desc:
      '世界上有许多著名的侦探机构，其中最著名的是平克顿和伯恩斯调查局（后来合并成一家公司）。这样的公司一般有两类工作人员：安保人员和调查人员。',
    credit: [20, 45],
    duty: ['格斗（斗殴）', '射击', '法律', '图书馆', '心理学', '潜行', '追踪'],
    dutySkill: '教育*2+(力量>敏捷?力量*2:敏捷*2)',
    dutySkillExt: '一项社交技能',
    dutySkillOptions: ['魅惑', '话术', '恐吓', '说服'],
  },
  {
    name: '精神病医生（古典）',
    desc:
      '1920 年代，“精神病医生”这个词专用来称呼治疗精神失常的医生（也就是早期的精神科医生）。精神分析在当时的美国鲜为人知，而且它的基本内容都是性生活和如厕训练之类令大众不齿的东西。精神病学，一种正规的从行为主义发展来的医学理论则要普及得多。精神病医生、精神科医生和神经科医生还经常爆发激烈的论战。',
    credit: [10, 60],
    duty: [
      '法律',
      '聆听',
      '医学',
      '外语',
      '精神分析',
      '心理学',
      '科学（生物学，化学）',
    ],
    dutySkill: '教育*4',
  },
  {
    name: '动物训练师',
    desc:
      '动物训练师可能在电影工作室、巡回马戏团、马厩工作或自由工作。不管是训练导盲犬、狮子钻火圈，他们工作时基本要独自一人长时间近距离地照看这些动物。动物训练师可以像对人一样对动物使用「心理学」技能。',
    credit: [10, 40],
    duty: [
      '跳跃',
      '聆听',
      '博物学',
      '动物驯养',
      '科学（动物学）',
      '潜行',
      '追踪',
    ],
    dutySkill: '教育*2+(外貌>意志?外貌*2:意志*2)',
    dutySkillExt: '任意一项其他个人或时代特长',
  },
  {
    name: '文物学家（原作向）',
    desc:
      '文物学家也许是调查员可以从事的最具有洛夫克拉夫特风格的职业：那些历久弥新的的卓越作品、湮没在古代传说中的神奇力量，总能使他们乐在其中。独立的收入使文物学家能够研究古旧晦涩的文物，或者根据自己的兴趣爱好集中探寻特别的种类。他们通常有着欣赏的眼光、敏锐的头脑，和讽刺无知、自大、贪婪者的愚蠢时尖酸刻薄的幽默。',
    credit: [30, 70],
    duty: ['估价', '艺术 / 工艺（任一）', '历史', '图书馆', '外语', '侦查'],
    dutySkill: '教育*4',
    dutySkillExt: '一项社交技能',
    dutySkillOptions: ['魅惑', '话术', '恐吓', '说服'],
  },
  {
    name: '古董商',
    desc: '',
    credit: [30, 50],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '考古学家（原作向）',
    desc: '',
    credit: [10, 40],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '建筑师',
    desc: '',
    credit: [30, 70],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '艺术家',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '精神病院看护',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '运动员',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '作家（原作向）',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '酒保',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '猎人',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '书商',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '赏金猎人',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '拳击手、摔跤手',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '管家、男仆、女仆',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '神职人员',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '计算机程序员、工程师(现代)',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '黑客(现代)',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '牛仔',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '工匠',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '罪犯-刺客',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '罪犯-银行劫匪',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '罪犯-打手、暴徒',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '罪犯-窃贼',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '罪犯-欺诈师',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '罪犯-独行罪犯',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '罪犯-女飞贼（古典）',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '罪犯-赃物贩子',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '罪犯-赝造者、伪造者',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '罪犯-走私者',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '罪犯-混混',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '教团首领',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '除魅师（现代）',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '设计师',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '业余艺术爱好者（原作向）',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '潜水员',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '医生（原作向）',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '流浪者',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '司机-私人司机',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '司机-司机',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '编辑',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '政府官员',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '工程师',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '艺人',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '探险家（古典）',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '农民',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '联邦探员',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '消防员',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '驻外记者',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '法医',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '赌徒',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '黑帮-黑帮老大',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '黑帮-马仔',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '绅士、淑女',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '游民',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '勤杂护工',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '记者（原作向）-调查记者',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '记者（原作向）-通讯记者',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '法官',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '工人',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '律师',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '图书馆管理员（原作向）',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '技师',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '军官',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '传教士',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '登山家',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '博物馆管理员',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '音乐家',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '护士',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '神秘学家',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '旅行家',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '超心理学家',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '药剂师',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '摄影师-摄影师',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '摄影师-摄影记者',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '飞行员-飞行员',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '飞行员-特技飞行员（古典）',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '警探',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '警官',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '私家侦探',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '教授（原作向）',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '淘金客',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '性工作者',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '精神病学家',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '心理学家、心理分析学家',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '研究员',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '海员-军舰海员',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '海员-民用船海员',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '推销员',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '科学家',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '秘书',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '店老板',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '士兵、海军陆战队士兵',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '间谍',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '学生、实习生',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '替身演员',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '部落成员',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '殡葬师',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '工会活动家',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '服务生',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '白领工人-职员/主管',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '白领工人-中层、高层管理人员',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '狂热者',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
  {
    name: '饲养员',
    desc: '',
    credit: [],
    duty: [],
    dutySkill: '教育*4',
  },
];

JSON.parse(JSON.stringify(job));
