import { register } from '../tags';
import Col from './Col';
import Define from './Define';
import Input from './Input';
import Row from './Row';
import Select from './Select';
import Tabs from './Tabs';
import TextArea from './TextArea';
import Use from './Use';
import BaseInfo from './BaseInfo';
import Template from './Template';

register(Col);
register(Define);
register(Input);
register(Row);
register(Select);
register(Tabs);
register(TextArea);
register(Use);
register(BaseInfo);
register(Template);
