module.exports = {
  GET_TEMPLATE_SUCCESS: 'GET_TEMPLATE_SUCCESS',
  FIND_TEMPLATE_SUCCESS: 'FIND_TEMPLATE_SUCCESS',
  CREATE_TEMPLATE_SUCCESS: 'CREATE_TEMPLATE_SUCCESS',
  UPDATE_TEMPLATE_SUCCESS: 'UPDATE_TEMPLATE_SUCCESS',
  REMOVE_TEMPLATE_SUCCESS: 'REMOVE_TEMPLATE_SUCCESS',
  SET_EDITED_TEMPLATE: 'SET_EDITED_TEMPLATE',
  SELECT_TEMPLATE: 'SELECT_TEMPLATE',
  CREATE_ACTOR_SUCCESS: 'CREATE_ACTOR_SUCCESS',
  GET_ACTOR_SUCCESS: 'GET_ACTOR_SUCCESS',
  SELECT_ACTOR: 'SELECT_ACTOR',
  REMOVE_ACTOR_SUCCESS: 'REMOVE_ACTOR_SUCCESS',
  UPDATE_ACTOR_SUCCESS: 'UPDATE_ACTOR_SUCCESS',
};
