module.exports = {
  EXAMPLE: 'EXAMPLE',
  SHOW_ALERT: 'SHOW_ALERT',
  HIDE_ALERT: 'HIDE_ALERT',
  SHOW_LOADING: 'SHOW_LOADING',
  HIDE_LOADING: 'HIDE_LOADING',
  ADD_CONVERSES: 'ADD_CONVERSES',
  ADD_MSG: 'ADD_MSG',
}
