export default {
  ADD_NOTE: 'ADD_NOTE',
  GET_NOTE: 'GET_NOTE',
  SWITCH_NOTE: 'SWITCH_NOTE',
  SAVE_NOTE: 'SAVE_NOTE',
  UPDATE_NOTE: 'UPDATE_NOTE',
  SYNC_NOTE_REQUEST: 'SYNC_NOTE_REQUEST',
  SYNC_NOTE_SUCCESS: 'SYNC_NOTE_SUCCESS',
  SYNC_NOTE_FAILED: 'SYNC_NOTE_FAILED',
};
