module.exports = {
  SET_USER_SETTINGS: 'SET_USER_SETTINGS',
  SET_SYSTEM_SETTINGS: 'SET_SYSTEM_SETTINGS',
  UPDATE_NOTIFICATION_PERMISSION: 'UPDATE_NOTIFICATION_PERMISSION',
  ADD_FAVORITE_DICE: 'ADD_FAVORITE_DICE',
  UPDATE_FAVORITE_DICE: 'UPDATE_FAVORITE_DICE',
}
