name: "relative-ci"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - release

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn install
      - name: build
        run: yarn run build:ci
      - name: Push to RelativeCI
        env:
          RELATIVE_CI_KEY: ${{ secrets.RELATIVE_CI_KEY }}
        run: npx relative-ci-agent
